-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cabac_top_cabac_top_Pipeline_VITIS_LOOP_40_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    streamCtxRAM_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    streamCtxRAM_full_n : IN STD_LOGIC;
    streamCtxRAM_write : OUT STD_LOGIC );
end;


architecture behav of cabac_top_cabac_top_Pipeline_VITIS_LOOP_40_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_A60 : STD_LOGIC_VECTOR (11 downto 0) := "101001100000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_1F0 : STD_LOGIC_VECTOR (8 downto 0) := "111110000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_7E : STD_LOGIC_VECTOR (8 downto 0) := "001111110";
    constant ap_const_lv7_7E : STD_LOGIC_VECTOR (6 downto 0) := "1111110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_3F : STD_LOGIC_VECTOR (6 downto 0) := "0111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln40_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal I_FRAME_INIT_VALS_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal I_FRAME_INIT_VALS_ce0 : STD_LOGIC;
    signal I_FRAME_INIT_VALS_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal streamCtxRAM_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln12_fu_132_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln12_reg_297 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln_reg_302 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln14_3_fu_212_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln14_3_reg_307 : STD_LOGIC_VECTOR (8 downto 0);
    signal initState_fu_240_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal initState_reg_313 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_reg_319 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_cast_fu_122_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_78 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln40_fu_116_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_2_fu_136_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln_fu_146_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal and_ln14_1_fu_158_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln14_2_fu_166_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln14_1_fu_170_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln14_1_fu_154_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln14_fu_176_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_192_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln14_fu_203_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln14_2_fu_206_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln14_fu_199_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln8_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln8_fu_223_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln14_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln13_fu_230_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal xor_ln16_fu_256_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln16_fu_261_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln16_fu_266_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cabac_top_cabac_top_Pipeline_VITIS_LOOP_40_1_I_FRAME_INIT_VALS_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cabac_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    I_FRAME_INIT_VALS_U : component cabac_top_cabac_top_Pipeline_VITIS_LOOP_40_1_I_FRAME_INIT_VALS_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => I_FRAME_INIT_VALS_address0,
        ce0 => I_FRAME_INIT_VALS_ce0,
        q0 => I_FRAME_INIT_VALS_q0);

    flow_control_loop_pipe_sequential_init_U : component cabac_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln40_fu_110_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_78 <= add_ln40_fu_116_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_78 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    add_ln14_3_reg_307(8 downto 1) <= add_ln14_3_fu_212_p2(8 downto 1);
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                initState_reg_313 <= initState_fu_240_p3;
                tmp_reg_319 <= initState_fu_240_p3(6 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln12_reg_297 <= trunc_ln12_fu_132_p1;
                trunc_ln_reg_302 <= add_ln14_fu_176_p2(11 downto 4);
            end if;
        end if;
    end process;
    add_ln14_3_reg_307(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    I_FRAME_INIT_VALS_address0 <= i_cast_fu_122_p1(3 - 1 downto 0);

    I_FRAME_INIT_VALS_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            I_FRAME_INIT_VALS_ce0 <= ap_const_logic_1;
        else 
            I_FRAME_INIT_VALS_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln14_1_fu_170_p2 <= std_logic_vector(unsigned(zext_ln14_2_fu_166_p1) + unsigned(ap_const_lv12_A60));
    add_ln14_2_fu_206_p2 <= std_logic_vector(signed(sext_ln14_fu_203_p1) + signed(ap_const_lv9_1F0));
    add_ln14_3_fu_212_p2 <= std_logic_vector(unsigned(add_ln14_2_fu_206_p2) + unsigned(zext_ln14_fu_199_p1));
    add_ln14_fu_176_p2 <= std_logic_vector(unsigned(add_ln14_1_fu_170_p2) + unsigned(zext_ln14_1_fu_154_p1));
    add_ln40_fu_116_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv3_1));
    and_ln14_1_fu_158_p3 <= (tmp_2_fu_136_p4 & ap_const_lv5_0);
    and_ln_fu_146_p3 <= (tmp_2_fu_136_p4 & ap_const_lv7_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, streamCtxRAM_full_n)
    begin
                ap_block_pp0_stage0_01001 <= ((streamCtxRAM_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, streamCtxRAM_full_n)
    begin
                ap_block_pp0_stage0_11001 <= ((streamCtxRAM_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, streamCtxRAM_full_n)
    begin
                ap_block_pp0_stage0_subdone <= ((streamCtxRAM_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter4_assign_proc : process(streamCtxRAM_full_n)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (streamCtxRAM_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln40_fu_110_p2)
    begin
        if (((icmp_ln40_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_78, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_78;
        end if; 
    end process;

    i_cast_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_2),64));
    icmp_ln14_fu_234_p2 <= "1" when (unsigned(select_ln8_fu_223_p3) < unsigned(ap_const_lv9_7E)) else "0";
    icmp_ln40_fu_110_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv3_5) else "0";
    icmp_ln8_fu_218_p2 <= "1" when (signed(add_ln14_3_reg_307) < signed(ap_const_lv9_1)) else "0";
    initState_fu_240_p3 <= 
        trunc_ln13_fu_230_p1 when (icmp_ln14_fu_234_p2(0) = '1') else 
        ap_const_lv7_7E;
    select_ln16_fu_266_p3 <= 
        xor_ln16_fu_256_p2 when (tmp_reg_319(0) = '1') else 
        sub_ln16_fu_261_p2;
    select_ln8_fu_223_p3 <= 
        ap_const_lv9_1 when (icmp_ln8_fu_218_p2(0) = '1') else 
        add_ln14_3_reg_307;
        sext_ln14_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_302),9));

    shl_ln_fu_192_p3 <= (trunc_ln12_reg_297 & ap_const_lv3_0);

    streamCtxRAM_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, streamCtxRAM_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            streamCtxRAM_blk_n <= streamCtxRAM_full_n;
        else 
            streamCtxRAM_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    streamCtxRAM_din <= (select_ln16_fu_266_p3 & tmp_reg_319);

    streamCtxRAM_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            streamCtxRAM_write <= ap_const_logic_1;
        else 
            streamCtxRAM_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln16_fu_261_p2 <= std_logic_vector(unsigned(ap_const_lv7_3F) - unsigned(initState_reg_313));
    tmp_2_fu_136_p4 <= I_FRAME_INIT_VALS_q0(7 downto 4);
    trunc_ln12_fu_132_p1 <= I_FRAME_INIT_VALS_q0(4 - 1 downto 0);
    trunc_ln13_fu_230_p1 <= select_ln8_fu_223_p3(7 - 1 downto 0);
    xor_ln16_fu_256_p2 <= (initState_reg_313 xor ap_const_lv7_40);
    zext_ln14_1_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln_fu_146_p3),12));
    zext_ln14_2_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln14_1_fu_158_p3),12));
    zext_ln14_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_192_p3),9));
end behav;
